const data = {
  products: [
    {
      name: "Things Fall Apart",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 120,
      countInStock: 10,
      brand: "xPublisher",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Jane Eyre",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 100,
      countInStock: 20,
      brand: "xPublisher",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "The Color Purple",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 220,
      countInStock: 0,
      brand: "xPublisher",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Early in Orcadia",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 78,
      countInStock: 15,
      brand: "xPublisher",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Invisible Islands",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 65,
      countInStock: 5,
      brand: "xPublisher",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "The Blackhouse",
      category: "Novel",
      image: "/frontend/public/images/book.png",
      price: 139,
      countInStock: 12,
      brand: "xPublisher",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
